// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLECFeeo_4ZfNSa_b0jBKSTGtK6lpOBVw',
    appId: '1:22598174933:web:645bca503fea88ab837a5c',
    messagingSenderId: '22598174933',
    projectId: 'resell-prod',
    authDomain: 'resell-prod.firebaseapp.com',
    storageBucket: 'resell-prod.firebasestorage.app',
    measurementId: 'G-MSLZ20G906',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKAtziwyC8JBuuiqZzKv_hxQxHPVroOY8',
    appId: '1:22598174933:ios:f3ac823d0859f006837a5c',
    messagingSenderId: '22598174933',
    projectId: 'resell-prod',
    storageBucket: 'resell-prod.firebasestorage.app',
    iosClientId: '22598174933-j4krb95jrsgbe6dps6egqh9o7fj1los0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fksFanShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLECFeeo_4ZfNSa_b0jBKSTGtK6lpOBVw',
    appId: '1:22598174933:web:0f3adab251e70fab837a5c',
    messagingSenderId: '22598174933',
    projectId: 'resell-prod',
    authDomain: 'resell-prod.firebaseapp.com',
    storageBucket: 'resell-prod.firebasestorage.app',
    measurementId: 'G-NPFKQ3S37N',
  );

}