// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5YRU2h_c27wREraDqQbxgVrSI2dsFHmk',
    appId: '1:457269019522:web:7fc0cef9429d27bacc059b',
    messagingSenderId: '457269019522',
    projectId: 'resell-dev-a3869',
    authDomain: 'resell-dev-a3869.firebaseapp.com',
    storageBucket: 'resell-dev-a3869.firebasestorage.app',
    measurementId: 'G-TFW322MVL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_cQHnPhdIMMH4ddtDoA7EfkvsXbzn9I4',
    appId: '1:457269019522:android:96f408f4145501c5cc059b',
    messagingSenderId: '457269019522',
    projectId: 'resell-dev-a3869',
    storageBucket: 'resell-dev-a3869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4uHPax6-JDB-aj-G3Dl6t59aJXJNJpAQ',
    appId: '1:457269019522:ios:23d57afa8a9981becc059b',
    messagingSenderId: '457269019522',
    projectId: 'resell-dev-a3869',
    storageBucket: 'resell-dev-a3869.firebasestorage.app',
    iosBundleId: 'com.example.fksFanShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4uHPax6-JDB-aj-G3Dl6t59aJXJNJpAQ',
    appId: '1:457269019522:ios:23d57afa8a9981becc059b',
    messagingSenderId: '457269019522',
    projectId: 'resell-dev-a3869',
    storageBucket: 'resell-dev-a3869.firebasestorage.app',
    iosBundleId: 'com.example.fksFanShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5YRU2h_c27wREraDqQbxgVrSI2dsFHmk',
    appId: '1:457269019522:web:fc03ed4f4bf261e7cc059b',
    messagingSenderId: '457269019522',
    projectId: 'resell-dev-a3869',
    authDomain: 'resell-dev-a3869.firebaseapp.com',
    storageBucket: 'resell-dev-a3869.firebasestorage.app',
    measurementId: 'G-VE04S31316',
  );
}
